#ifndef __RCURSES_H__
#define __RCURSES_H__

#include <stdio.h>
#include <stdlib.h>
#include <dos.h>
#include <conio.h>

#include "rcurses/include/win_line.h"
#include "rcurses/include/attrib.h"

#include "rcurses/include/init_sys.h"

#include "rcurses/include/put_text.h"

#include "rcurses/include/keyproc.h"

#include "rcurses/include/low_1.h"
#include "rcurses/include/low_2.h"

#include "rcurses/include/high_1.h"

#include "rcurses/include/struct.h"

#endif  //      __RCURSES_H__
